/* Generated by automated build script */
#define SNAPSHOT
#define TEXTVER "Development snapshot 2017-01-31.9c3700a"
#define SSHVER "PuTTY-Snapshot-2017-01-31.9c3700a"
#define BINARY_VERSION 0,67,1337,0
#define SOURCE_COMMIT "9c3700a6d3d037bd823a65f5837264605891b2ea"
